# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs: 
  build:
    docker: 
      - image: gridlabd/slac-master:190828
    steps: 
      - checkout 
      - run: 
          name: Run version check
          command: |
            gridlabd --version
            gridlabd --origin
      - run:
          name: Run the simulation
          command: |
            sh main.sh
      - store_artifacts: 
            path: /root/project
